### PR TITLE
ELK, ES validation

### PR DESCRIPTION
**Pull request by redspart**
Can hit:
- ELK
- ES Nodes

### CODE REVIEW

**Comment by redspart** [comment]
@tanderegg Can access ELK now!

**Comment by tanderegg** [comment]
@redspart I am able to run, and get to Kibana, but I'm experiencing some weird behavior.  If I run `vagrant up elk es1 es1 es3` as normal, the `elk` job will run as expected, but `es1` through `es2` all seem to target the same container, and so they return `ok` for most everything, and the additional 3 containers that should be configured remain untouched, which is why Elasticsearch itself doesn't work.  If I run them one at a time, like `vagrant elk`, then `vagrant es1`, etc., then everything does deploy to the right containers, and works as expected.  I'll keep looking into this, but have you experienced the same phenomenon?

**Comment by redspart** [comment]
Hi @tanderegg,

I see the phenomenon you are describing, however, I have found a few more odd behaviours:
- `vagrant up elk es1 es2 es3 --no-parallel`, causes the issue you are describing, reprovisioning each one fixes it. 
- `vagrant up elk es1 es2 es3`, fails on a lock file, however, I can validate the changes to each container are unique
- `vagrant up elk es`, no issues (can hit both Kibana and ES)
- Running each command individually has no problems.

Ran on:
- Ansible 2.8.0
- Vagrant 2.2.6
- Docker 19.03.12

I'll keep investigating to see what's going on.

**Comment by tanderegg** [comment]
@redspart Thanks for testing, one quick thing to note, you can run `curl https://localhost:9200/_cluster/health` to make sure ES is fully functional, it should return `status: green` if so.  Running `vagrant up elk` alone will result in ES responding to htttp requests, but it won't be `green` since it has no master nodes without `es1 es2 es3` as well.

**Review by tanderegg — APPROVED** [review]

**Pull request merged**
